#!/bin/bash
# =============================================================================
# 00-setup-usb.sh
# Prepares a USB drive for AOSP build (formats as ext4, mounts it)
# AOSP REQUIRES a case-sensitive filesystem - NTFS/FAT32 will NOT work!
# =============================================================================

set -e

echo "============================================"
echo " USB Drive Setup for AOSP Build"
echo "============================================"
echo ""
echo "WARNING: This will ERASE ALL DATA on the selected drive!"
echo "AOSP requires a case-sensitive filesystem (ext4)."
echo ""

# ---------------------------------------------------------------------------
# 1. List available drives
# ---------------------------------------------------------------------------
echo "Available drives:"
echo ""
lsblk -o NAME,SIZE,TYPE,MOUNTPOINT,LABEL,FSTYPE | grep -E "disk|part" || true
echo ""

# ---------------------------------------------------------------------------
# 2. Select drive
# ---------------------------------------------------------------------------
echo "Enter the device to use (e.g., sdb, sdc):"
echo "DO NOT include /dev/ or partition numbers"
read -rp "Device: " USB_DEVICE

USB_PATH="/dev/${USB_DEVICE}"
PART_PATH="${USB_PATH}1"

if [ ! -b "$USB_PATH" ]; then
    echo "ERROR: Device $USB_PATH does not exist!"
    exit 1
fi

echo ""
echo "You selected: $USB_PATH"
echo "ALL DATA ON THIS DRIVE WILL BE DESTROYED!"
read -rp "Type 'YES' to confirm: " CONFIRM

if [ "$CONFIRM" != "YES" ]; then
    echo "Aborted."
    exit 0
fi

# ---------------------------------------------------------------------------
# 3. Unmount any existing partitions
# ---------------------------------------------------------------------------
echo ""
echo "[1/5] Unmounting existing partitions..."
for part in $(lsblk -ln -o NAME "$USB_PATH" | tail -n +2); do
    sudo umount "/dev/${part}" 2>/dev/null || true
done

# ---------------------------------------------------------------------------
# 4. Create partition table + single ext4 partition
# ---------------------------------------------------------------------------
echo "[2/5] Creating partition table..."
sudo parted -s "$USB_PATH" mklabel gpt

echo "[3/5] Creating ext4 partition..."
sudo parted -s "$USB_PATH" mkpart primary ext4 0% 100%

# Wait for partition to appear
sleep 2

echo "[4/5] Formatting as ext4..."
sudo mkfs.ext4 -F -L AOSP_BUILD "$PART_PATH"

# ---------------------------------------------------------------------------
# 5. Mount the drive
# ---------------------------------------------------------------------------
echo "[5/5] Mounting drive..."

MOUNT_POINT="/mnt/aosp-build"
sudo mkdir -p "$MOUNT_POINT"
sudo mount "$PART_PATH" "$MOUNT_POINT"

# Make it owned by current user
sudo chown -R "$USER:$USER" "$MOUNT_POINT"

# ---------------------------------------------------------------------------
# 6. Copy repository to USB drive (so scripts are available in WSL)
# ---------------------------------------------------------------------------
echo ""
echo "[6/6] Copying build repository to USB drive..."
REPO_SRC="$(cd "$(dirname "$0")/.." && pwd)"
REPO_DST="$MOUNT_POINT/androidtv-rock4cplus-repo"

if [ -d "$REPO_SRC" ]; then
    mkdir -p "$REPO_DST"
    cp -r "$REPO_SRC"/* "$REPO_DST/" 2>/dev/null || true
    cp -r "$REPO_SRC"/.* "$REPO_DST/" 2>/dev/null || true
    echo "Repository copied to: $REPO_DST"
    echo "You can now run scripts from WSL using:"
    echo "  cd $REPO_DST && ./scripts/01-setup-environment.sh"
else
    echo "WARNING: Could not find repository source at $REPO_SRC"
fi

# ---------------------------------------------------------------------------
# 7. Add to fstab for auto-mount on boot
# ---------------------------------------------------------------------------
echo ""
echo "Adding to /etc/fstab for auto-mount on boot..."
UUID=$(sudo blkid -s UUID -o value "$PART_PATH")

if ! grep -q "$UUID" /etc/fstab; then
    echo "UUID=$UUID $MOUNT_POINT ext4 defaults,noatime 0 2" | sudo tee -a /etc/fstab
fi

# ---------------------------------------------------------------------------
# 8. Save config
# ---------------------------------------------------------------------------
CONFIG_FILE="$(dirname "$0")/../.build-config"
mkdir -p "$(dirname "$CONFIG_FILE")"

cat > "$CONFIG_FILE" << EOF
# AOSP Build Configuration
# Generated by 00-setup-usb.sh on $(date)

# Work directory (on USB drive)
WORK_DIR=$MOUNT_POINT/androidtv-rock4cplus

# Repository directory (copy on USB drive)
REPO_DIR=$REPO_DST

# USB mount point
USB_MOUNT=$MOUNT_POINT
USB_DEVICE=$USB_PATH
USB_UUID=$UUID
EOF

# Also create .build-config in the USB repo copy so scripts work from there too
if [ -n "$REPO_DST" ] && [ -d "$REPO_DST" ]; then
    cat > "$REPO_DST/.build-config" << EOF
# AOSP Build Configuration
# Generated by 00-setup-usb.sh on $(date)

# Work directory (on USB drive)
WORK_DIR=$MOUNT_POINT/androidtv-rock4cplus

# Repository directory (copy on USB drive)
REPO_DIR=$REPO_DST

# USB mount point
USB_MOUNT=$MOUNT_POINT
USB_DEVICE=$USB_PATH
USB_UUID=$UUID
EOF
    echo "Created .build-config in USB repo copy"
fi

echo ""
echo "============================================"
echo " USB Setup Complete!"
echo "============================================"
echo ""
echo "Drive: $USB_PATH"
echo "Mount: $MOUNT_POINT"
echo "UUID:  $UUID"
echo ""
echo "AOSP work dir:  $MOUNT_POINT/androidtv-rock4cplus"
echo "Repo copy:      $REPO_DST"
echo ""
echo "Config saved to: $CONFIG_FILE"
echo ""
echo "Next step: Run 01-setup-environment.sh"
echo "  From Windows: ./scripts/01-setup-environment.sh"
echo "  From WSL:     cd $REPO_DST && ./scripts/01-setup-environment.sh"
echo ""
