#!/bin/bash
# =============================================================================
# 02-download-source.sh
# Downloads AOSP Android source + Rockchip BSP for ROCK 4C+
# Each BSP downloads to its own subdirectory under /mnt/aosp-build/
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Base mount point
BASE_DIR="${BASE_DIR:-/mnt/aosp-build}"

# Optionally load .build-config if it exists (for custom paths)
CONFIG_FILE="$SCRIPT_DIR/../.build-config"
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi

REPO_TOOL="$SCRIPT_DIR/../repo-local"
REPO_CMD="repo"

download_repo_tool() {
    echo "Downloading repo tool..."
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo -o "$REPO_TOOL"
    elif command -v wget >/dev/null 2>&1; then
        wget -qO "$REPO_TOOL" https://storage.googleapis.com/git-repo-downloads/repo
    else
        echo "ERROR: curl or wget is required to download the repo tool."
        exit 1
    fi
    chmod a+x "$REPO_TOOL"
}

if ! command -v repo >/dev/null 2>&1; then
    if [ ! -x "$REPO_TOOL" ]; then
        download_repo_tool
    fi
    REPO_CMD="$REPO_TOOL"
fi

echo "============================================"
echo " Downloading Android Source Code"
echo " Target: Radxa ROCK 4C+ (RK3399-T)"
echo "============================================"
echo ""

# ---------------------------------------------------------------------------
# Choose build option
# ---------------------------------------------------------------------------
echo "Available Android BSP sources for RK3399:"
echo ""
echo "  1) Android 9 Pie (Radxa, OFFICIALLY SUPPORTED)"
echo "     - Manifest: radxa/manifests, branch: rockpi-box-9.0"
echo "     - Most stable, all hardware works"
echo "     - Directory: $BASE_DIR/androidtv-rock4cplus-radxa9"
echo ""
echo "  2) Android 11 (Radxa rk11, kernel 4.19) ★ RECOMMENDED"
echo "     - Manifest: radxa/manifests, branch: Android11_Radxa_rk11"
echo "     - Best built on Ubuntu 18.04 (Python 2 native, no 2to3 needed)"
echo "     - Directory: $BASE_DIR/androidtv-rock4cplus-radxa11"
echo ""
echo "  3) Android 12 (Vicharak BSP, kernel 5.10) EXPERIMENTAL"
echo "     - Manifest: vicharak-in/rockchip-android-manifest (GitHub)"
echo "     - Full Rockchip BSP included, no separate downloads needed"
echo "     - Directory: $BASE_DIR/androidtv-rock4cplus-vicharak12"
echo ""
echo "  4) Android 12 AOSP (pure Google, EXPERIMENTAL)"
echo "     - No Rockchip BSP — manual integration required"
echo "     - Directory: $BASE_DIR/androidtv-rock4cplus-aosp12"
echo ""
read -rp "Enter choice [1-4]: " BUILD_CHOICE

# ---------------------------------------------------------------------------
# Set BSP-specific work directory
# ---------------------------------------------------------------------------
case $BUILD_CHOICE in
    1) WORK_DIR="$BASE_DIR/androidtv-rock4cplus-radxa9" ;;
    2) WORK_DIR="$BASE_DIR/androidtv-rock4cplus-radxa11" ;;
    3) WORK_DIR="$BASE_DIR/androidtv-rock4cplus-vicharak12" ;;
    4) WORK_DIR="$BASE_DIR/androidtv-rock4cplus-aosp12" ;;
    *) echo "Invalid choice. Exiting."; exit 1 ;;
esac

# Save BSP choice and work dir for other scripts
mkdir -p "$SCRIPT_DIR/.."
cat > "$SCRIPT_DIR/../.build-config" << CFGEOF
# Generated by 02-download-source.sh
BSP_CHOICE=$BUILD_CHOICE
WORK_DIR=$WORK_DIR
BASE_DIR=$BASE_DIR
CFGEOF
echo "Saved config: BSP=$BUILD_CHOICE, WORK_DIR=$WORK_DIR"

# ---------------------------------------------------------------------------
# Create working directory
# ---------------------------------------------------------------------------
echo ""
echo "[1/4] Creating working directory: $WORK_DIR"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

case $BUILD_CHOICE in
    1)
        # ====================================================================
        # OPTION 1: Android 9 Pie (Officially supported by Radxa)
        # ====================================================================
        echo "[2/4] Initializing repo with Radxa Android 9 Pie manifest..."
        echo ""
        echo "Manifest: https://github.com/radxa/manifests.git"
        echo "Branch:   rockpi-box-9.0"
        echo "XML:      rockpi-release.xml"
        echo ""

        "$REPO_CMD" init --depth=1 \
            -u https://github.com/radxa/manifests.git \
            -b rockpi-box-9.0 \
            -m rockpi-release.xml

        echo ""
        echo "============================================"
        echo " GitHub Authentication Required"
        echo "============================================"
        echo ""
        echo "If GitHub asks for username/password:"
        echo "  - Username: your GitHub username"
        echo "  - Password: **Personal Access Token (PAT)** (NOT your password)"
        echo ""
        echo "To create a PAT:"
        echo "  1. Go to https://github.com/settings/tokens"
        echo "  2. Click 'Generate new token (classic)'"
        echo "  3. Set 'repo' scope"
        echo "  4. Copy the token and use it as password"
        echo ""
        echo "============================================"
        echo ""

        echo "[3/4] Syncing repositories (this will take a while)..."
        echo "Estimated download: ~80GB"
        echo ""
        "$REPO_CMD" sync -c -j$(nproc) --no-tags --no-clone-bundle

        echo "[4/4] Downloading additional tools..."
        # rkbin is already included in Radxa manifest, no need to clone separately
        echo "rkbin is included in Radxa manifest, skipping manual clone"
        ;;

    3)
        # ====================================================================
        # OPTION 3: Android 12 (Vicharak BSP, kernel 5.10) ★ BEST
        # ====================================================================
        echo "[2/4] Initializing repo with Vicharak Android 12 manifest..."
        echo ""
        echo "Manifest: https://github.com/vicharak-in/rockchip-android-manifest"
        echo "Branch:   master"
        echo "XML:      rockchip-s-vicharak.xml"
        echo ""

        "$REPO_CMD" init --no-tags --no-clone-bundle \
            -u https://github.com/vicharak-in/rockchip-android-manifest \
            -b master \
            -m rockchip-s-vicharak.xml

        echo "[3/4] Syncing repositories (this will take a while)..."
        echo "Estimated download: ~80GB"
        echo ""

        # First attempt: sync with reduced parallelism to avoid rate limits
        "$REPO_CMD" sync -j4 --no-clone-bundle || {
            echo ""
            echo "=== Sync had errors, fixing known issues ==="
            echo ""

            # Fix 1: prebuilts/sdk often fails on AOSP mirrors — clone directly from Google
            if [ ! -d "prebuilts/sdk/.git" ]; then
                echo "Cloning prebuilts/sdk from Google's official source..."
                rm -rf prebuilts/sdk
                mkdir -p prebuilts
                git clone --depth=1 https://android.googlesource.com/platform/prebuilts/sdk prebuilts/sdk || {
                    echo "Google source failed, trying Tsinghua mirror..."
                    rm -rf prebuilts/sdk
                    git clone --depth=1 https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/prebuilts/sdk prebuilts/sdk
                }
            fi

            # Fix 2: Retry remaining repos with single thread
            echo "Retrying remaining repos..."
            "$REPO_CMD" sync -j1 --no-clone-bundle --fail-fast || {
                echo "Some repos still failed. Retrying one more time..."
                "$REPO_CMD" sync -j1 -c --no-clone-bundle
            }
        }

        echo "[4/4] Copying Android kernel configs..."
        if [ -d "mkcombinedroot/configs" ]; then
            cp -vr mkcombinedroot/configs/android-1* kernel-5.10/arch/arm64/configs/ 2>/dev/null || true
            echo "Kernel configs copied."
        fi
        echo ""
        echo "Vicharak BSP ready. Device config at: device/rockchip/rk3399"
        ;;

    4)
        # ====================================================================
        # OPTION 4: Android 12 AOSP (Experimental, automatic Rockchip overlay)
        # ====================================================================
        echo "[2/4] Initializing repo with AOSP Android 12 manifest..."
        echo ""
        echo "Manifest: https://android.googlesource.com/platform/manifest"
        echo "Branch:   android-12.1.0_r11"
        echo ""
        echo "NOTICE: This downloads AOSP core and installs a Rockchip BSP overlay automatically."
        echo "Some device tuning may still be required, but the initial BSP components will be installed."
        echo ""

        "$REPO_CMD" init --depth=1 \
            -u https://android.googlesource.com/platform/manifest \
            -b android-12.1.0_r11

        echo "[3/4] Syncing repositories (this will take a while)..."
        echo "Estimated download: ~60GB"
        echo ""
        "$REPO_CMD" sync -c -j$(nproc) --no-tags --no-clone-bundle

        echo "[4/4] Downloading Rockchip BSP overlay..."
        mkdir -p "$WORK_DIR/device/rockchip"
        mkdir -p "$WORK_DIR/hardware/rockchip"
        mkdir -p "$WORK_DIR/tools"
        mkdir -p "$WORK_DIR/vendor/rockchip"

        if [ ! -d "$WORK_DIR/device/rockchip/rk3399" ]; then
            git clone --depth=1 https://github.com/khadas/android_device_rockchip_rk3399.git "$WORK_DIR/device/rockchip/rk3399" || true
        fi
        if [ ! -d "$WORK_DIR/device/rockchip/common" ]; then
            git clone --depth=1 https://github.com/khadas/android_device_rockchip_common.git "$WORK_DIR/device/rockchip/common" || true
        fi
        if [ ! -d "$WORK_DIR/hardware/rockchip" ]; then
            git clone --depth=1 https://github.com/lineageos-on-rockchip/android_hardware_rockchip.git "$WORK_DIR/hardware/rockchip" || true
        fi
        if [ ! -d "$WORK_DIR/kernel" ]; then
            git clone --depth=1 https://github.com/rockchip-linux/kernel.git "$WORK_DIR/kernel" || true
        fi
        if [ ! -d "$WORK_DIR/tools/rkbin" ]; then
            git clone --depth=1 https://github.com/rockchip-linux/rkbin.git "$WORK_DIR/tools/rkbin" || true
        fi
        if [ ! -d "$WORK_DIR/vendor/rockchip/mpp" ]; then
            git clone --depth=1 https://github.com/rockchip-linux/mpp.git "$WORK_DIR/vendor/rockchip/mpp" || true
        fi

        echo "[4/4] Applying local ROCK 4C+ files..."
        if [ -f "$SCRIPT_DIR/../configs/BoardConfig.mk" ] && [ -d "$WORK_DIR/device/rockchip/rk3399" ]; then
            cp -f "$SCRIPT_DIR/../configs/BoardConfig.mk" "$WORK_DIR/device/rockchip/rk3399/BoardConfig.mk"
        fi
        if [ -f "$SCRIPT_DIR/../patches/rk3399-rock-4c-plus.dts" ] && [ -d "$WORK_DIR/kernel/arch/arm64/boot/dts/rockchip" ]; then
            cp -f "$SCRIPT_DIR/../patches/rk3399-rock-4c-plus.dts" "$WORK_DIR/kernel/arch/arm64/boot/dts/rockchip/"
        fi
        ;;

    2)
        # ====================================================================
        # OPTION 2: Android 11 (Radxa rk11, kernel 4.19)
        # ====================================================================
        echo "[2/4] Initializing repo with Radxa Android 11 manifest..."
        echo ""
        echo "Manifest: https://github.com/radxa/manifests.git"
        echo "Branch:   Android11_Radxa_rk11"
        echo "XML:      rockchip-r-release.xml"
        echo ""
        echo "NOTE: Android 11 builds best on Ubuntu 18.04 LTS (Python 2 native)."
        echo ""

        "$REPO_CMD" init --depth=1 \
            -u https://github.com/radxa/manifests.git \
            -b Android11_Radxa_rk11 \
            -m rockchip-r-release.xml

        echo ""
        echo "[3/4] Syncing repositories (this will take a while)..."
        echo "Estimated download: ~80GB"
        echo ""
        "$REPO_CMD" sync -c -j$(nproc) --no-tags --no-clone-bundle

        echo "[4/4] Android 11 source ready."
        echo ""
        echo "Radxa Android 11 BSP ready. Device config at: device/rockchip/rk3399"
        ;;

    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================"
echo " Source download complete!"
echo "============================================"
echo ""
echo "Source location: $WORK_DIR"
echo ""

# Print disk usage
# echo "Disk usage:"
# du -sh "$WORK_DIR" 2>/dev/null || true
# echo ""

echo "Next step: Run 03-configure-build.sh"
echo ""
