#!/bin/bash
# =============================================================================
# 02-download-source.sh
# Downloads AOSP Android source + Rockchip BSP for ROCK 4C+
# Each BSP downloads to its own subdirectory under /mnt/aosp-build/
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Base mount point
BASE_DIR="${BASE_DIR:-/mnt/aosp-build}"

# Optionally load .build-config if it exists (for custom paths)
CONFIG_FILE="$SCRIPT_DIR/../.build-config"
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi

echo "============================================"
echo " Downloading Android Source Code"
echo " Target: Radxa ROCK 4C+ (RK3399-T)"
echo "============================================"
echo ""

# ---------------------------------------------------------------------------
# Choose build option
# ---------------------------------------------------------------------------
echo "Available Android BSP sources for RK3399:"
echo ""
echo "  1) Android 9 Pie (Radxa, OFFICIALLY SUPPORTED)"
echo "     - Manifest: radxa/manifests, branch: rockpi-box-9.0"
echo "     - Most stable, all hardware works"
echo "     - Directory: $BASE_DIR/androidtv-rock4cplus-radxa9"
echo ""
echo "  2) Android 12 (Vicharak BSP, kernel 5.10) ★ RECOMMENDED"
echo "     - Manifest: vicharak-in/rockchip-android-manifest (GitHub)"
echo "     - Full Rockchip BSP included, no separate downloads needed"
echo "     - Directory: $BASE_DIR/androidtv-rock4cplus-vicharak12"
echo ""
echo "  3) Android 12 (Advantech BSP, kernel 4.19.232)"
echo "     - Manifest: ADVANTECH-Rockchip Azure DevOps"
echo "     - Requires separate prebuilts/external downloads"
echo "     - Directory: $BASE_DIR/androidtv-rock4cplus-advantech12"
echo ""
echo "  4) Android 12 AOSP (pure Google, EXPERIMENTAL)"
echo "     - No Rockchip BSP — manual integration required"
echo "     - Directory: $BASE_DIR/androidtv-rock4cplus-aosp12"
echo ""
read -rp "Enter choice [1-4]: " BUILD_CHOICE

# ---------------------------------------------------------------------------
# Set BSP-specific work directory
# ---------------------------------------------------------------------------
case $BUILD_CHOICE in
    1) WORK_DIR="$BASE_DIR/androidtv-rock4cplus-radxa9" ;;
    2) WORK_DIR="$BASE_DIR/androidtv-rock4cplus-vicharak12" ;;
    3) WORK_DIR="$BASE_DIR/androidtv-rock4cplus-advantech12" ;;
    4) WORK_DIR="$BASE_DIR/androidtv-rock4cplus-aosp12" ;;
    *) echo "Invalid choice. Exiting."; exit 1 ;;
esac

# Save BSP choice and work dir for other scripts
mkdir -p "$SCRIPT_DIR/.."
cat > "$SCRIPT_DIR/../.build-config" << CFGEOF
# Generated by 02-download-source.sh
BSP_CHOICE=$BUILD_CHOICE
WORK_DIR=$WORK_DIR
BASE_DIR=$BASE_DIR
CFGEOF
echo "Saved config: BSP=$BUILD_CHOICE, WORK_DIR=$WORK_DIR"

# ---------------------------------------------------------------------------
# Create working directory
# ---------------------------------------------------------------------------
echo ""
echo "[1/4] Creating working directory: $WORK_DIR"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

case $BUILD_CHOICE in
    1)
        # ====================================================================
        # OPTION 1: Android 9 Pie (Officially supported by Radxa)
        # ====================================================================
        echo "[2/4] Initializing repo with Radxa Android 9 Pie manifest..."
        echo ""
        echo "Manifest: https://github.com/radxa/manifests.git"
        echo "Branch:   rockpi-box-9.0"
        echo "XML:      rockpi-release.xml"
        echo ""

        repo init --depth=1 \
            -u https://github.com/radxa/manifests.git \
            -b rockpi-box-9.0 \
            -m rockpi-release.xml

        echo ""
        echo "============================================"
        echo " GitHub Authentication Required"
        echo "============================================"
        echo ""
        echo "If GitHub asks for username/password:"
        echo "  - Username: your GitHub username"
        echo "  - Password: **Personal Access Token (PAT)** (NOT your password)"
        echo ""
        echo "To create a PAT:"
        echo "  1. Go to https://github.com/settings/tokens"
        echo "  2. Click 'Generate new token (classic)'"
        echo "  3. Set 'repo' scope"
        echo "  4. Copy the token and use it as password"
        echo ""
        echo "============================================"
        echo ""

        echo "[3/4] Syncing repositories (this will take a while)..."
        echo "Estimated download: ~80GB"
        echo ""
        repo sync -c -j$(nproc) --no-tags --no-clone-bundle

        echo "[4/4] Downloading additional tools..."
        mkdir -p "$WORK_DIR/tools"
        # Radxa uses rkbin from GitLab, not GitHub
        # Only clone if directory doesn't exist or is empty
        if [ ! -d "$WORK_DIR/rkbin" ] || [ -z "$(ls -A "$WORK_DIR/rkbin" 2>/dev/null)" ]; then
            echo "Cloning rkbin from GitLab..."
            git clone --depth=1 https://gitlab.com/rk-vendor/rk/rkbin.git "$WORK_DIR/rkbin" || true
        else
            # Check if it's the correct repo
            if [ -d "$WORK_DIR/rkbin/.git" ]; then
                REMOTE_URL=$(cd "$WORK_DIR/rkbin" && git remote get-url origin 2>/dev/null || true)
                if [[ "$REMOTE_URL" == *"gitlab.com/rk-vendor/rk/rkbin"* ]]; then
                    echo "rkbin already exists, updating..."
                    cd "$WORK_DIR/rkbin" && git pull --rebase || true
                else
                    echo "WARNING: rkbin exists but is from a different repo"
                    echo "Please remove it manually if you want to use the correct one"
                fi
            else
                echo "WARNING: rkbin exists but is not a git repo"
                echo "Please remove it manually if you want to use the correct one"
            fi
        fi
        ;;

    2)
        # ====================================================================
        # OPTION 2: Android 12 (Vicharak BSP, kernel 5.10) ★ BEST
        # ====================================================================
        echo "[2/4] Initializing repo with Vicharak Android 12 manifest..."
        echo ""
        echo "Manifest: https://github.com/vicharak-in/rockchip-android-manifest"
        echo "Branch:   master"
        echo "XML:      rockchip-s-vicharak.xml"
        echo ""

        repo init --no-tags --no-clone-bundle \
            -u https://github.com/vicharak-in/rockchip-android-manifest \
            -b master \
            -m rockchip-s-vicharak.xml

        echo "[3/4] Syncing repositories (this will take a while)..."
        echo "Estimated download: ~80GB"
        echo ""

        # First attempt: sync with reduced parallelism to avoid rate limits
        repo sync -j4 --no-clone-bundle || {
            echo ""
            echo "=== Sync had errors, fixing known issues ==="
            echo ""

            # Fix 1: prebuilts/sdk often fails on AOSP mirrors — clone directly from Google
            if [ ! -d "prebuilts/sdk/.git" ]; then
                echo "Cloning prebuilts/sdk from Google's official source..."
                rm -rf prebuilts/sdk
                mkdir -p prebuilts
                git clone --depth=1 https://android.googlesource.com/platform/prebuilts/sdk prebuilts/sdk || {
                    echo "Google source failed, trying Tsinghua mirror..."
                    rm -rf prebuilts/sdk
                    git clone --depth=1 https://mirrors.tuna.tsinghua.edu.cn/git/AOSP/platform/prebuilts/sdk prebuilts/sdk
                }
            fi

            # Fix 2: Retry remaining repos with single thread
            echo "Retrying remaining repos..."
            repo sync -j1 --no-clone-bundle --fail-fast || {
                echo "Some repos still failed. Retrying one more time..."
                repo sync -j1 -c --no-clone-bundle
            }
        }

        echo "[4/4] Copying Android kernel configs..."
        if [ -d "mkcombinedroot/configs" ]; then
            cp -vr mkcombinedroot/configs/android-1* kernel-5.10/arch/arm64/configs/ 2>/dev/null || true
            echo "Kernel configs copied."
        fi
        echo ""
        echo "Vicharak BSP ready. Device config at: device/rockchip/rk3399"
        ;;

    3)
        # ====================================================================
        # OPTION 3: Android 12 (Advantech BSP for RK3399)
        # ====================================================================
        echo "[2/4] Initializing repo with Advantech Android 12 manifest..."
        echo ""
        echo "Manifest: https://kag-sw.visualstudio.com/RK3399-Android/_git/android-s12-manifest"
        echo "Branch:   rk3399-androidS12"
        echo "XML:      default.xml"
        echo ""

        # Advantech uses a custom repo tool
        echo "Cloning Advantech repo tool..."
        git clone https://github.com/ADVANTECH-Rockchip/repo.git "$WORK_DIR/../adv-repo" || true

        if [ -d "$WORK_DIR/../adv-repo" ]; then
            REPO_CMD="$WORK_DIR/../adv-repo/repo"
        else
            REPO_CMD="repo"
        fi

        $REPO_CMD init -u \
            https://kag-sw.visualstudio.com/RK3399-Android/_git/android-s12-manifest \
            -b rk3399-androidS12 \
            -m default.xml

        echo "[3/4] Syncing repositories (this will take a while)..."
        echo "Estimated download: ~80GB"
        echo ""
        $REPO_CMD sync -c -f --no-clone-bundle -j$(nproc)

        echo ""
        echo "============================================"
        echo " IMPORTANT: Download prebuilts & external!"
        echo "============================================"
        echo ""
        echo "The Advantech BSP requires additional tarballs:"
        echo ""
        echo "  Dropbox:"
        echo "    prebuilts: https://www.dropbox.com/scl/fi/plwys31je681795kt4fvy/prebuilts-rk3399-AndroidS12-20230518.tar.gz"
        echo "    external:  https://www.dropbox.com/scl/fi/lszmpsjr9mqhm8xxpxhmp/external-rk3399-AndroidS12-20230522.tar.gz"
        echo ""
        echo "  Baidu (Key: 1234):"
        echo "    https://pan.baidu.com/s/1jDOMJTM6jTNGqpNdgNKC7w?pwd=1234"
        echo ""
        echo "After downloading, extract them into the source tree:"
        echo "  tar zxvf prebuilts-rk3399-AndroidS12-20230518.tar.gz -C $WORK_DIR/"
        echo "  tar zxvf external-rk3399-AndroidS12-20230522.tar.gz -C $WORK_DIR/"
        echo ""
        ;;

    4)
        # ====================================================================
        # OPTION 4: Android 12 AOSP (Experimental, no official BSP)
        # ====================================================================
        echo "[2/4] Initializing repo with AOSP Android 12 manifest..."
        echo ""
        echo "Manifest: https://android.googlesource.com/platform/manifest"
        echo "Branch:   android-12.1.0_r11"
        echo ""
        echo "WARNING: This is pure AOSP without Rockchip BSP."
        echo "You will need to manually add:"
        echo "  - Rockchip kernel (4.19/5.10)"
        echo "  - Mali GPU drivers"
        echo "  - Rockchip HALs (gralloc, hwcomposer, etc.)"
        echo "  - Device tree for ROCK 4C+"
        echo ""

        repo init --depth=1 \
            -u https://android.googlesource.com/platform/manifest \
            -b android-12.1.0_r11

        echo "[3/4] Syncing repositories (this will take a while)..."
        echo "Estimated download: ~60GB"
        echo ""
        repo sync -c -j$(nproc) --no-tags --no-clone-bundle

        echo "[4/4] Downloading Rockchip BSP components..."
        mkdir -p "$WORK_DIR/vendor/rockchip"
        git clone --depth=1 https://github.com/rockchip-linux/kernel.git "$WORK_DIR/kernel" || true
        git clone --depth=1 https://github.com/rockchip-linux/tools.git "$WORK_DIR/tools/rkbin" || true
        git clone --depth=1 https://github.com/rockchip-linux/mpp.git "$WORK_DIR/vendor/rockchip/mpp" || true
        ;;
    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "============================================"
echo " Source download complete!"
echo "============================================"
echo ""
echo "Source location: $WORK_DIR"
echo ""

# Print disk usage
echo "Disk usage:"
du -sh "$WORK_DIR" 2>/dev/null || true
echo ""

echo "Next step: Run 03-configure-build.sh"
echo ""
